import Header from "@/app/(Navbar)/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/app/(Navbar)/Footer";
import Provider from "./Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <Provider>
          <main className=" flex flex-col justify-between overflow-hidden bg-white backdrop-blur-lg bg-opacity-30 p-8 m-5 rounded-md">
            <Header />
            <div className="">{children}</div>
            <Footer />
          </main>
        </Provider>
      </body>
    </html>
  );
}
